import { auth } from "@/auth";
import { Footer } from "@/components/Footer";
import Topbar from "@/components/Topbar";
import type { Metadata } from "next";

// TODO: Chance it
export const metadata: Metadata = {
  title: "Root",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <>
      <Topbar session={session} />
      {children}
      <Footer />
    </>
  );
}
