import { Footer } from "@/components/Footer";
import Topbar from "@/components/Topbar";
import { TailwindIndicator } from "@/components/ui/tailwind-indicator";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Root",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Topbar />
      {children}
      <Footer />
    </>
  );
}
